---
engines:
  csslint:
    enabled: true
    checks:
      important:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    checks:
      no-unused-expressions:
        enabled: false
      wrap-iife:
        enabled: false
  fixme:
    enabled: true
  markdownlint:
    enabled: true
    checks:
      MD032:
        enabled: false
      MD033:
        enabled: false
    exclude_fingerprints:
    - 5ab721b3ceef47076888b2c9d6d2138b
    - fd127de9679324370afaa6412e27d77f
ratings:
  paths:
  - "**.css"
  - "**.html"
  - "**.js"
  - "**.md"
exclude_paths:
  - "./bower_components/"
